version: '3'
services:
  api:
    container_name: fwa_container
    image: fwa
    build: ./
    ports:
      - "80:8080"
    networks:
      - myNetwork

  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: myUser
      POSTGRES_PASSWORD: myPassword
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - myNetwork
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.ru
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - myNetwork
    restart: unless-stopped

networks:
  myNetwork:
    driver: bridge

volumes:
  postgres:
  pgadmin: